name: google_map_location_picker_example
description: Demonstrates how to use the google_map_location_picker plugin.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.1.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  tflite: ^1.0.6
  camera: ^0.5.8+2
  image_picker: ^0.6.7+1
  url_launcher: ^5.4.10
  
  firebase_core: ^0.3.4
  firebase_analytics: ^2.1.1+3

  cloud_firestore: ^0.10.1

  firebase_auth: ^0.8.4+5
  google_sign_in: ^4.0.1+1

  rxdart: ^0.21.0
  provider: ^4.1.3 
  font_awesome_flutter: 8.4.0

  google_map_location_picker: ^3.3.3
  
  flutter_sms: 2.0.0+2 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  
  pit_sms_call_log: ^0.1.3
  
  permission_handler: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  
    - assets/
    - assets/mapStyle.json
  
    - assets/models/
    - assets/texts/
    - assets/images/
    
    - assets/covers/
    - assets/congrats.gif
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
